
name: update report.txt

on:
  schedule:
    - cron: "0/10 0 * * *"
  push:
  pull_request:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update report
        run: |
          date > report.txt
      - name: save report
        uses: actions/upload-artifact@v2
        with:
          name: report.txt
          path: report.txt
