name: search topics

on:
  schedule:
    - cron: "0/15 * * * *"
  push:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: search
        run: |
          PATH=./node_modules/.bin:$PATH
          npm i graphqurl
          ./search.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}