name: search topics

on:
  schedule:
    - cron: "30 * * * *"
  push:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: search
        run: |
          PATH=./node_modules/.bin:$PATH
          npm i graphqurl >& npm-i-graphqurl.log
          ./search.sh
          cat search.json | jq "[.data.search.repos | .[] | .repo | {login:.owner.login, name:.name}]" > report.json
          sed -i "s/^/    /" report.json
          echo search-topic.yml report > issue
          echo >> issue
          echo header >> issue
          echo >> issue
          cat report.json >> issue
          hub issue update 1 -F issue
          head issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
